try(require("shiny") || install.packages("shiny"))
try(require("nFactors") || install.packages("nFactors"))
try(require("qgraph") || install.packages("qgraph"))
try(require("corrplot") || install.packages("corrplot"))
try(require(wordcloud) || install.packages("wordcloud"))
try(require(ggraph) || install.packages("ggraph"))
try(require(igraph) || install.packages("igraph"))
try(require(lattice) || install.packages("lattice"))
try(require(textrank) || install.packages("textrank"))
try(require(udpipe) || install.packages("udpipe"))

library("shiny")
library("nFactors")
library("qgraph")
library("corrplot")
library("ggraph")
library("igraph")
library("lattice")
library("textrank")
library("udpipe")
library("wordcloud")
